social_auth_google.settings:
  type: config_object
  label: 'Social Auth Google settings'
  mapping:
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'App Secret'
    graph_version:
      type: float
      label: 'Google Graph API version'
